---
apiVersion: v1
kind: Namespace
metadata:
  name: observability-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: input-resource-reader
  namespace: vmware-system-tmc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: input-resource-reader
  namespace: vmware-system-tmc
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secret
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: input-resource-reader
  namespace: vmware-system-tmc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: input-resource-reader
subjects:
- kind: ServiceAccount
  name: input-resource-reader
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: cluster-name-secret
  namespace: vmware-system-tmc
spec:
  serviceAccountName: input-resource-reader # used to fetch input resources
  inputResources:
  - name: config
    ref:
      apiVersion: v1
      kind: ConfigMap
      name: stack-config
  template:
    type: generic
    stringData:
      cluster_name: $(.config.data.cluster_name)
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: cluster-name-secret
  namespace: vmware-system-tmc
spec:
  toNamespace: '*'
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: cluster-name-secret
  namespace: tanzu-continuousdelivery-resources
spec:
  fromNamespace: vmware-system-tmc
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: wavefront-secret
  namespace: observability-system
spec:
  serviceAccountName: input-resource-reader # used to fetch input resources
  inputResources:
  - name: secret
    ref:
      apiVersion: v1
      kind: Secret
      name: wavefront-secret
  template:
    data:
      token: $(.wavefront-secret.data.token)
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: wavefront-secret
  namespace: vmware-system-tmc
spec:
  toNamespace: '*'
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: wavefront-sercret
  namespace: observability-system
spec:
  fromNamespace: vmware-system-tmc