apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/
  - wavefront.yaml

configMapGenerator:
  - name: pve-configmap
    namespace: observability-system
    literals:
      - cluster_name="pve-tkgm-wk1"