# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
# resources:
#   - ../../base/
#   - wavefront.yaml

# configMapGenerator:
#   - name: cluster-config
#     literals:
#       - CLUSTER_NAME=pve-tkgm-wk1  

# vars:
#   - name: CLUSTER_NAME
#     objref:
#       kind: ConfigMap
#       name: cluster-config
#       apiVersion: v1
#     fieldref:
#       fieldpath: data.CLUSTER_NAME